spring.application.name=tasks-app
#--- db properties -------------
spring.datasource.pgsql.jdbcUrl=jdbc:postgresql://localhost:5432/sn_tasks_db?currentSchema=tasks_app
spring.datasource.pgsql.username=postgres
spring.datasource.pgsql.password=Shreyu@66
spring.datasource.pgsql.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.mongodb.uri=mongodb+srv://sn_dev:Shreyu66@sn.segyz.mongodb.net/
spring.data.mongodb.database=sn_db


