spring.application.name=tasks-app
#--- db properties -------------
spring.datasource.url=jdbc:postgresql://localhost:5432/sn_tasks_db?currentSchema=tasks_app
spring.datasource.username=postgres
spring.datasource.password=Shreyu@66
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
